### ISSUE TITLE
NMS Util Spiral Curve

### ISSUE THREAD

**Issue by Mike-Blackwell** [laanp/NMS-Util#1]
I'm able to create the spiral in Curve Creator tab, then when I go to Object Along Curve; select an object and the newly created curve, I see only one object but in the Collection it show a number of object created but not along the spiral curve. I was able to successfully create using the wave and other curves but spiral doesn't seem to work as expected.

**Comment by laanp** [comment]
Hi Mike, 
I noticed this as well, the trick is to select the spiral and the switch to Edit mode and then back to object mode, they will then appear…!
I will be looking at the obect along curve module to add a fix…

**Comment by Mike-Blackwell** [comment]
Works like a champ! Once your know the handshake, thanxs Mike

**Comment by laanp** [comment]
Version 1.14 corrects this issue

**Comment by Mike-Blackwell** [comment]
Thanxs for the 1.14 update, Peter...

I see that you've enclosed my floating base with accompanying message bubble, my apologies for overstepping by using available examples within Blender. I didn't realize that this was an issue and didn't expect it to make a confrontation. Other than saying I'm sorry and did realize permissions were necessary I will refrain from using your designs with exception of the GEK building, I really like it if you don't mine,

v/r
Mike
